name: Pull Request CI

on:
  pull_request:
    branches:
      - '*'
    types: [labeled, synchronize]

jobs:
  trigger-service-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check if service label exists
        id: check-label
        run: |
          json_input='{"label": {"name": "example-service-modified"}}'
          LABEL=$(jq -r '.label.name' <<< "$json_input")
          echo $LABEL
          
          if [[ "$LABEL" == *-modified ]]; then
            SERVICE=${LABEL%-modified}
          else
            SERVICE=$LABEL
          fi
          
          echo "name={service}" >> $GITHUB_OUTPUT
#          echo "::set-output name=service::$SERVICE"

      - name: Trigger CI for labeled service
        if: ${{ steps.check-label.outputs.service }}
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
            SERVICE=${{ steps.check-label.outputs.service }}
            gh workflow run "${SERVICE}-ci.yml" -f pr_number=${{ github.event.number }}