name: Pull Request Label CI

on:
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, reopened]

jobs:
  labelPR:
    name: Add microservice modified label in PR
    runs-on: ubuntu-latest

    steps:
      - name: Add label
        uses: TinkurLab/monorepo-pr-labeler-action@4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          suffix: '-modified'

      - name: Test
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          labels=$(gh pr view "${{ github.event.pull_request.number }}" --json labels -q '.labels|map(.name)')
          echo "labels: $labels"