name: Pull Request CI

on:
  pull_request:
    branches:
      - '*'
    types: [labeled, synchronize]

jobs:
  trigger-service-workflows:
    name: Trigger CI for labeled service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if service label exists
        id: check-label
        run: |
          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}')
          
          # Extract label names that end with '-modified' and remove the suffix
          modified_labels=$(echo "$labels" | jq -r '.[] | select(.name | endswith("-modified")) | .name | rtrimstr("-modified")')

          # Check if there are modified labels
          if [ -z "$modified_labels" ]; then
            echo "No modified labels found."
            exit 0
          fi

          # Join labels into a single string separated by spaces
          modified_labels_string=$(echo "$modified_labels" | tr '\n' ' ')
          echo "modified_labels=$modified_labels_string" >> $GITHUB_ENV

      - name: Trigger CI for labeled service
        if: ${{ steps.check-label.outputs.service }}
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          IFS=' ' read -r -a services <<< "$modified_labels"
          for service in "${services[@]}"; do
            echo "Triggering CI/CD for: $service"
            gh workflow run "${service}-ci.yml" -f pr_number=${{ github.event.pull_request.number }}
          done