name: Pull Request CI

on:
  pull_request:
    branches:
      - '*'
    types: [labeled, synchronize]

jobs:
  trigger-service-workflows:
    name: Trigger CI for labeled service
    runs-on: ubuntu-latest

    steps:
      - name: Check if service label exists
        id: check-label
        run: |
          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}')
          
          # Extract label names using jq
          modified_labels=$(echo "$labels" | jq -r '.[] | select(.name | endswith("-modified")) | .name | rtrimstr("-modified")')
          
          # Set the modified labels as an output if not empty
          if [[ -n "$modified_labels" ]]; then
              echo "::set-output name=service::$modified_labels"
          fi

      - name: Trigger CI for labeled service
        if: ${{ steps.check-label.outputs.service }}
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
            SERVICE=${{ steps.check-label.outputs.service }}
            gh workflow run "${SERVICE}-ci.yml" -f pr_number=${{ github.event.number }}